#!/usr/bin/env bash
echo "---"
read -p "Project name? [MYMAGENTO2] " project_name
read -p "PHP version? [7.0] " php_version
echo "---"
if [ "$project_name" == "" ]; then
    project_name="MYMAGENTO2"
fi
if [ "$php_version" == "" ]; then
	php_version="7.0"
fi

domain=$(echo "$project_name"  | sed 's/[^[[:alnum:]]]*//g')
read -p "Do you want to create http://$domain.local? [n] " -n 1 -r create_domain
if [ "$create_domain" == "y" ]; then
	echo "-----------"
	read -p "Docker Server IP? [127.0.0.1] " server_ip
	echo "-----------"
	if [ "$server_ip" == "" ]; then
		server_ip="127.0.0.1"
	fi
fi 

echo "-----------"
echo "Installing project: $project_name [PHP $php_version]"
echo "-----------"
git clone https://github.com/redstage/docker-linux-m2-v2.git;
mv docker-linux-m2-v2 $project_name;
cd $project_name;
mkdir src;

if [ "$create_domain" == "y" ]; then
	sed -i '' -e "s/\#  ServerName dev/$domain/g" .docker/config/magento.conf;
	sed -i '' -e "s/\#  ServerAlias www.dev/$domain/g" .docker/config/magento.conf;
	sed -i '' -e "s/\#  ServerName dev/$domain/g" .docker/config/magento.ssl.conf;
	sed -i '' -e "s/\#  ServerAlias www.dev/$domain/g" .docker/config/magento.ssl.conf;	
	sudo echo "$server_ip  $domain.local" >> /etc/hosts
	sudo echo "$server_ip  www.$domain.local" >> /etc/hosts
fi 

./init $project_name $php_version;

echo "---"
read -p "Do you want to install Magento? [n] " -n 1 -r install_magento
if [ "$install_magento" == "y" ]; then
    echo "---"
    read -p "Magento Version to install [2.3.1] " magento_version
    echo "---"
    rm -rf src/*
    
    if [ "$magento_version" == "" ]; then
	magento_version="2.3.1"
    fi
    docker-compose exec --user root "apache" install-magento2 $magento_version
fi 
