#!/usr/bin/env bash
echo "---"
read -p "Project name? [MYMAGENTO2] " project_name
read -p "PHP version? [7.0] " php_version
echo "---"
if [ "$project_name" == "" ]; then
    project_name="MYMAGENTO2"
fi
if [ "$php_version" == "" ]; then
	php_version="7.0"
fi
echo "-----------"
echo "Installing project: $project_name [PHP $php_version]"
echo "-----------"
git clone https://github.com/redstage/docker-linux-m2-v2.git;
mv docker-linux-m2-v2 $project_name;
cd $project_name;
mkdir src;
./init $project_name $php_version;

echo "---"
read -p "Do you want to install Magento? [n] " -n 1 -r install_magento
if [ "$install_magento" == "y" ]; then
    echo "---"
    read -p "Magento Version to install [2.3.1] " magento_version
    echo "---"
    rm -rf src/*
    
    if [ "$magento_version" == "" ]; then
	magento_version="2.3.1"
    fi
    docker-compose exec --user root "apache" install-magento2 $magento_version
fi 
