#!/usr/bin/env bash
read -p "Project name? [MYMAGENTO2] " project_name
read -p "PHP version? [7.0] " php_version
if [ "$project_name" == "" ]; then
    project_name="MYMAGENTO2"
fi
if [ "$php_version" == "" ]; then
	php_version="7.0"
fi
echo "-----------"
echo "Installing project: $project_name [PHP $php_version]"
echo "-----------"
git clone https://github.com/redstage/docker-linux-m2-v2.git;
mv docker-linux-m2-v2 $project_name;
cd $project_name;
./init $project_name $php_version;
